# Generated by Django 6.0.5 on 2026-06-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentmatchschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tournamentmatchschedule',
            name='court',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchschedule',
            name='match',
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='match_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='match_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('called', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.court')),
                ('round_robin_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.roundrobinmatch')),
                ('tournament_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tournamentmatch')),
            ],
            options={
                'ordering': ['court', 'order'],
                'unique_together': {('court', 'order')},
            },
        ),
        migrations.DeleteModel(
            name='MatchSchedule',
        ),
        migrations.DeleteModel(
            name='TournamentMatchSchedule',
        ),
    ]
