# Generated by Django 6.0.6 on 2026-06-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tournamentmatchschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pair',
            options={'ordering': ['display_order', 'pair_code'], 'verbose_name': 'リーグ枠', 'verbose_name_plural': 'リーグ枠'},
        ),
    ]
