# Generated by Django 6.0.6 on 2026-06-20 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stage_group_stage_tournamentbracket_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancementSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('league_rank', 'リーグ順位'), ('tournament_result', 'トーナメント結果')], max_length=30)),
                ('source_rank', models.IntegerField(blank=True, null=True)),
                ('source_result', models.CharField(blank=True, choices=[('winner', '勝者'), ('loser', '敗者')], max_length=20)),
                ('source_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.group')),
                ('source_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tournamentmatch')),
                ('source_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stage')),
                ('target_league_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advancement_source', to='core.leagueentry')),
                ('target_tournament_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advancement_source', to='core.tournamententry')),
            ],
        ),
    ]
