# Generated by Django 6.0.6 on 2026-06-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_group_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leagueentry',
            unique_together={('group', 'pair_code')},
        ),
    ]
