# Generated by Django 6.0.6 on 2026-06-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_schedulereplacementhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('category', 'カテゴリ'), ('schedule_block', '日程区分'), ('tournament', '大会')], max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('snapshot_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('schedule_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.scheduleblock')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
