# Generated by Django 6.0.6 on 2026-06-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tournamentbracket_score_display_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentbracket',
            name='layout_type',
            field=models.CharField(choices=[('split', '左右表示'), ('single', '片側表示')], default='single', max_length=20),
        ),
    ]
