# Generated by Django 6.0.6 on 2026-06-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_tournamentbracket_layout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='champion_display_mode',
            field=models.CharField(choices=[('auto', '自動'), ('horizontal_1line', '横書き1行'), ('vertical_1line', '縦書き1行'), ('none', '表示しない')], default='auto', max_length=30),
        ),
    ]
