# Generated by Django 6.0.6 on 2026-07-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_default_entry_display_mode_tournament_default_league_entry_display_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_tournament_layout_type',
            field=models.CharField(choices=[('single', '片側表示'), ('split', '左右表示')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentbracket',
            name='layout_type',
            field=models.CharField(choices=[('inherit', '大会デフォルトを使う'), ('split', '左右表示'), ('single', '片側表示')], default='inherit', max_length=20),
        ),
    ]
