# Generated by Django 6.0.6 on 2026-07-01 14:12

from django.db import migrations, models


def copy_existing_champion_defaults(apps, schema_editor):
    Tournament = apps.get_model("core", "Tournament")

    for tournament in Tournament.objects.all():
        tournament.default_single_champion_display_mode = (
            tournament.default_champion_display_mode
        )
        tournament.default_split_champion_display_mode = (
            tournament.default_champion_display_mode
        )
        tournament.default_single_champion_text_layout = (
            tournament.default_champion_text_layout
        )
        tournament.default_split_champion_text_layout = (
            tournament.default_champion_text_layout
        )
        tournament.save(
            update_fields=[
                "default_single_champion_display_mode",
                "default_split_champion_display_mode",
                "default_single_champion_text_layout",
                "default_split_champion_text_layout",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_tournamentbracket_use_tournament_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_single_champion_display_mode',
            field=models.CharField(choices=[('auto', '自動'), ('horizontal_1line', '横書き1行'), ('vertical_1line', '縦書き1行'), ('none', '表示しない')], default='auto', max_length=30),
        ),
        migrations.AddField(
            model_name='tournament',
            name='default_single_champion_text_layout',
            field=models.CharField(choices=[('auto', '自動'), ('one_line', '1行'), ('name_org_2line', '名前/所属2段')], default='auto', max_length=30),
        ),
        migrations.AddField(
            model_name='tournament',
            name='default_split_champion_display_mode',
            field=models.CharField(choices=[('auto', '自動'), ('horizontal_1line', '横書き1行'), ('vertical_1line', '縦書き1行'), ('none', '表示しない')], default='auto', max_length=30),
        ),
        migrations.AddField(
            model_name='tournament',
            name='default_split_champion_text_layout',
            field=models.CharField(choices=[('auto', '自動'), ('one_line', '1行'), ('name_org_2line', '名前/所属2段')], default='auto', max_length=30),
        ),
        migrations.RunPython(
            copy_existing_champion_defaults,
            migrations.RunPython.noop,
        ),
    ]
