# Generated by Django 6.0.6 on 2026-07-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_leagueentry_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamententry',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='player1_name',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='player2_name',
        ),
    ]
