# Generated by Codex on 2026-07-12

from django.db import migrations, models


_DAMM_TABLE = (
    (0, 3, 1, 7, 5, 9, 8, 6, 4, 2),
    (7, 0, 9, 2, 1, 5, 4, 8, 6, 3),
    (4, 2, 0, 6, 8, 7, 1, 3, 5, 9),
    (1, 7, 5, 0, 9, 8, 3, 4, 2, 6),
    (6, 1, 2, 3, 0, 4, 5, 9, 7, 8),
    (3, 6, 7, 4, 2, 0, 9, 5, 8, 1),
    (5, 8, 6, 9, 7, 2, 0, 1, 3, 4),
    (8, 9, 4, 5, 3, 6, 2, 0, 1, 7),
    (9, 4, 3, 8, 6, 1, 7, 2, 0, 5),
    (2, 5, 8, 1, 4, 3, 6, 7, 9, 0),
)


def _damm_digit(number_text):
    interim = 0
    for char in number_text:
        interim = _DAMM_TABLE[interim][int(char)]
    return str(interim)


def _build_match_key(kind_digit, sequence_number):
    base = f"{kind_digit}{sequence_number}"
    return f"{base}{_damm_digit(base)}"


def populate_match_keys(apps, schema_editor):
    Tournament = apps.get_model("core", "Tournament")
    RoundRobinMatch = apps.get_model("core", "RoundRobinMatch")
    TournamentMatch = apps.get_model("core", "TournamentMatch")

    for tournament in Tournament.objects.all().order_by("id"):
        league_sequence = 1
        league_matches = (
            RoundRobinMatch.objects.filter(
                group__category__tournament=tournament,
            )
            .select_related(
                "group",
                "group__stage",
                "group__category",
            )
            .order_by(
                "group__stage__display_order",
                "group__display_order",
                "group__name",
                "meeting_number",
                "id",
            )
        )

        for match in league_matches:
            match.match_key = _build_match_key("1", league_sequence)
            match.save(update_fields=["match_key"])
            league_sequence += 1

        tournament_sequence = 1
        tournament_matches = (
            TournamentMatch.objects.filter(
                bracket__category__tournament=tournament,
            )
            .select_related(
                "bracket",
                "bracket__stage",
                "bracket__category",
            )
            .order_by(
                "bracket__stage__display_order",
                "bracket__display_order",
                "bracket__name",
                "round_number",
                "match_number",
                "id",
            )
        )

        for match in tournament_matches:
            match.match_key = _build_match_key("2", tournament_sequence)
            match.save(update_fields=["match_key"])
            tournament_sequence += 1


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_scheduleblock_result_input_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roundrobinmatch",
            name="match_key",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="match_key",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.RunPython(
            populate_match_keys,
            migrations.RunPython.noop,
        ),
    ]
