# Generated by Django 6.0.5 on 2026-05-18 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSheetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_key', models.CharField(default='standard', max_length=50)),
                ('use_base_pdf', models.BooleanField(default=True)),
                ('base_pdf_path', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_code', models.CharField(max_length=20)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('player1_name', models.CharField(max_length=100)),
                ('player2_name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'ordering': ['display_order', 'entry_code'],
                'unique_together': {('category', 'entry_code')},
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_code', models.CharField(max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('player1_name', models.CharField(max_length=100)),
                ('player2_name', models.CharField(max_length=100)),
                ('retired', models.BooleanField(default=False)),
                ('retired_reason', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.participant')),
            ],
            options={
                'ordering': ['display_order', 'pair_code'],
                'unique_together': {('category', 'pair_code')},
            },
        ),
        migrations.CreateModel(
            name='RoundRobinMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair1_games', models.IntegerField(blank=True, null=True)),
                ('pair2_games', models.IntegerField(blank=True, null=True)),
                ('match_games', models.IntegerField(default=7)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('pair1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_pair1', to='core.pair')),
                ('pair2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_pair2', to='core.pair')),
            ],
            options={
                'unique_together': {('group', 'pair1', 'pair2')},
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score_sheet_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.scoresheettemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament'),
        ),
        migrations.CreateModel(
            name='TournamentBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_code', models.CharField(max_length=20)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('player1_name', models.CharField(max_length=50)),
                ('player2_name', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournamentbracket')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.participant')),
                ('source_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pair')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('match_number', models.IntegerField()),
                ('pair1_games', models.IntegerField(blank=True, null=True)),
                ('pair2_games', models.IntegerField(blank=True, null=True)),
                ('match_games', models.IntegerField(default=7)),
                ('next_slot', models.CharField(blank=True, choices=[('pair1', '上側 / pair1'), ('pair2', '下側 / pair2')], max_length=10)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournamentbracket')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tournamentmatch')),
                ('pair1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pair1_tournament_matches', to='core.tournamententry')),
                ('pair2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pair2_tournament_matches', to='core.tournamententry')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournament_matches', to='core.tournamententry')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('game_diff', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pair')),
            ],
            options={
                'unique_together': {('group', 'pair')},
            },
        ),
        migrations.CreateModel(
            name='MatchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('called', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.court')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.roundrobinmatch')),
            ],
            options={
                'ordering': ['court', 'order'],
                'unique_together': {('court', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TournamentMatchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('called', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.court')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournamentmatch')),
            ],
            options={
                'ordering': ['court', 'order'],
                'unique_together': {('court', 'order')},
            },
        ),
    ]
