# Generated by Django 6.0.6 on 2026-06-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pair_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='layout_type',
            field=models.CharField(choices=[('split', '左右表示'), ('single', '片側表示')], default='split', max_length=20),
        ),
    ]
