# Generated by Django 6.0.6 on 2026-06-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_pair_to_leagueentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tournament', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentbracket',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamententry',
            unique_together={('bracket', 'display_order'), ('bracket', 'pair_code')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentmatch',
            unique_together={('bracket', 'match_code'), ('bracket', 'round_number', 'match_number')},
        ),
    ]
