# Generated by Django 6.0.6 on 2026-06-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_advancementsource'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('category', 'stage', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentbracket',
            unique_together={('category', 'stage', 'name')},
        ),
    ]
