# Generated by Django 6.0.6 on 2026-06-21 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_stage_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roundrobinmatch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='roundrobinmatch',
            name='counts_for_ranking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roundrobinmatch',
            name='meeting_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='roundrobinmatch',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='roundrobinmatch',
            unique_together={('group', 'pair1', 'pair2', 'meeting_number')},
        ),
    ]
