# Generated by Django 6.0.6 on 2026-06-22 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_roundrobinmatch_result_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleReplacementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_label', models.CharField(blank=True, max_length=200)),
                ('original_order', models.IntegerField()),
                ('original_called', models.BooleanField(default=False)),
                ('original_started', models.BooleanField(default=False)),
                ('original_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('original_court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.court')),
                ('original_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_original_histories', to='core.roundrobinmatch')),
                ('original_schedule_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.scheduleblock')),
                ('replacement_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_histories', to='core.roundrobinmatch')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_histories', to='core.schedule')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
