# Generated by Django 6.0.6 on 2026-06-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tournamentmatch_result_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='score_display_mode',
            field=models.CharField(choices=[('loser', '負けのみ'), ('both', '勝ち負け両方'), ('none', '表示しない')], default='loser', max_length=20),
        ),
    ]
