# Generated by Django 6.0.6 on 2026-06-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_tournamentbracket_champion_display_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='champion_text_layout',
            field=models.CharField(choices=[('auto', '自動'), ('one_line', '1行'), ('name_org_2line', '名前/所属2段')], default='auto', max_length=30),
        ),
    ]
