# Generated by Django 6.0.6 on 2026-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tournamentbracket_champion_text_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='entry_display_mode',
            field=models.CharField(choices=[('short_org_2line', '短い名前/所属2段'), ('one_line', '短い名前（所属）1行'), ('name_org_2line', 'フル名前/所属2段')], default='short_org_2line', max_length=30),
        ),
    ]
