# Generated by Django 6.0.6 on 2026-06-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tournamentbracket_entry_display_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='entry_display_mode',
            field=models.CharField(choices=[('inherit', '大会デフォルトを使う'), ('short_org_2line', '短い名前/所属2段'), ('one_line', '短い名前（所属）1行'), ('name_org_2line', 'フル名前/所属2段')], default='inherit', max_length=30),
        ),
    ]
