# Generated by Django 6.0.6 on 2026-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_stage_entry_display_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='entry_display_mode',
        ),
        migrations.AddField(
            model_name='tournament',
            name='default_entry_display_mode',
            field=models.CharField(choices=[('short_org_2line', '短い名前/所属2段'), ('one_line', '短い名前（所属）1行'), ('name_org_2line', 'フル名前/所属2段')], default='short_org_2line', max_length=30),
        ),
    ]
