# Generated by Django 6.0.6 on 2026-07-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_stage_entry_display_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentbracket',
            name='entry_display_mode',
            field=models.CharField(choices=[('inherit', '大会デフォルトを使う'), ('short_org_2line', '短い名前/所属2段'), ('one_line', '短い名前（所属）1行'), ('name_org_2line', 'フル名前/所属2段')], default='inherit', max_length=30),
        ),
    ]
