# Generated by Django 6.0.6 on 2026-07-01 12:59

from django.db import migrations, models


def copy_league_default_to_tournament_default(apps, schema_editor):
    Tournament = apps.get_model("core", "Tournament")

    for tournament in Tournament.objects.all():
        tournament.default_tournament_entry_display_mode = (
            tournament.default_league_entry_display_mode
        )
        tournament.save(update_fields=["default_tournament_entry_display_mode"])


def reverse_copy_tournament_default(apps, schema_editor):
    Tournament = apps.get_model("core", "Tournament")

    for tournament in Tournament.objects.all():
        tournament.default_league_entry_display_mode = (
            tournament.default_tournament_entry_display_mode
        )
        tournament.save(update_fields=["default_league_entry_display_mode"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_tournamentbracket_entry_display_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='default_entry_display_mode',
            new_name='default_league_entry_display_mode',
        ),
        migrations.AddField(
            model_name='tournament',
            name='default_tournament_entry_display_mode',
            field=models.CharField(choices=[('short_org_2line', '短い名前/所属2段'), ('one_line', '短い名前（所属）1行'), ('name_org_2line', 'フル名前/所属2段')], default='short_org_2line', max_length=30),
        ),
        migrations.RunPython(
            copy_league_default_to_tournament_default,
            reverse_copy_tournament_default,
        ),
    ]
