# Generated by Django 6.0.6 on 2026-07-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_tournament_default_tournament_layout_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_champion_display_mode',
            field=models.CharField(choices=[('auto', '自動'), ('horizontal_1line', '横書き1行'), ('vertical_1line', '縦書き1行'), ('none', '表示しない')], default='auto', max_length=30),
        ),
        migrations.AlterField(
            model_name='tournamentbracket',
            name='champion_display_mode',
            field=models.CharField(choices=[('inherit', '大会デフォルトを使う'), ('auto', '自動'), ('horizontal_1line', '横書き1行'), ('vertical_1line', '縦書き1行'), ('none', '表示しない')], default='inherit', max_length=30),
        ),
    ]
