# Generated by Django 6.0.6 on 2026-07-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_tournament_default_champion_display_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_tournament_score_display_mode',
            field=models.CharField(choices=[('loser', '負けのみ'), ('both', '勝ち負け両方'), ('none', '表示しない')], default='loser', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentbracket',
            name='score_display_mode',
            field=models.CharField(choices=[('inherit', '大会デフォルトを使う'), ('loser', '負けのみ'), ('both', '勝ち負け両方'), ('none', '表示しない')], default='inherit', max_length=20),
        ),
    ]
