# Generated by Django 6.0.6 on 2026-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tournament_default_tournament_score_display_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_champion_text_layout',
            field=models.CharField(choices=[('auto', '自動'), ('one_line', '1行'), ('name_org_2line', '名前/所属2段')], default='auto', max_length=30),
        ),
        migrations.AlterField(
            model_name='tournamentbracket',
            name='champion_text_layout',
            field=models.CharField(choices=[('inherit', '大会デフォルトを使う'), ('auto', '自動'), ('one_line', '1行'), ('name_org_2line', '名前/所属2段')], default='inherit', max_length=30),
        ),
    ]
