# Generated by Django 6.0.6 on 2026-07-01 13:54

from django.db import migrations, models


def preserve_existing_custom_settings(apps, schema_editor):
    TournamentBracket = apps.get_model("core", "TournamentBracket")

    TournamentBracket.objects.exclude(
        layout_type="inherit",
        score_display_mode="inherit",
        entry_display_mode="inherit",
        champion_display_mode="inherit",
        champion_text_layout="inherit",
    ).update(
        use_tournament_defaults=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_tournament_default_champion_text_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='use_tournament_defaults',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            preserve_existing_custom_settings,
            migrations.RunPython.noop,
        ),
    ]
