# Generated by Django 6.0.6 on 2026-07-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_category_public_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueentry',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='leagueentry',
            name='player1_name',
        ),
        migrations.RemoveField(
            model_name='leagueentry',
            name='player2_name',
        ),
    ]
