# Generated by Django 6.0.6 on 2026-07-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_tournamententry_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_league_score_color_mode',
            field=models.CharField(choices=[('colored', 'あり'), ('none', 'なし')], default='colored', max_length=20),
        ),
    ]
