# Generated by Django 6.0.6 on 2026-07-24 15:30

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_match_key_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='svg_split_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), core.models.validate_power_of_two]),
        ),
    ]
