# Generated by Django 6.0.6 on 2026-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_tournamentbracket_svg_split_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_tournament_score_color_mode',
            field=models.CharField(choices=[('black', '黒'), ('accent', 'アクセント色')], default='black', max_length=20),
        ),
    ]
