# Generated by Django 6.0.6 on 2026-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_tournament_default_score_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_tournament_reflected_entry_code_mode',
            field=models.CharField(choices=[('entry_code', '参加者entry_code'), ('slot_label', '後続枠slot_label')], default='entry_code', max_length=20),
        ),
    ]
