# Generated by Django 6.0.6 on 2026-08-30 11:53

import django.db.models.deletion
from django.db import migrations, models


def migrate_participant_names_and_organizations(apps, schema_editor):
    Participant = apps.get_model("core", "Participant")
    Tournament = apps.get_model("core", "Tournament")
    TournamentOrganizationField = apps.get_model(
        "core",
        "TournamentOrganizationField",
    )
    ParticipantOrganizationValue = apps.get_model(
        "core",
        "ParticipantOrganizationValue",
    )

    org1_by_tournament_id = {}

    for tournament in Tournament.objects.all():
        field, _ = TournamentOrganizationField.objects.get_or_create(
            tournament_id=tournament.id,
            code="org1",
            defaults={
                "label": "所属1",
                "display_order": 1,
                "is_active": True,
            },
        )
        org1_by_tournament_id[tournament.id] = field

    for participant in Participant.objects.select_related("category"):
        participant.original_player1_name = participant.player1_name
        participant.original_player2_name = participant.player2_name
        participant.current_player1_name = None
        participant.current_player1_short_name = None
        participant.current_player2_name = None
        participant.current_player2_short_name = None
        participant.has_day_player_change = False
        participant.save(
            update_fields=[
                "original_player1_name",
                "original_player2_name",
                "current_player1_name",
                "current_player1_short_name",
                "current_player2_name",
                "current_player2_short_name",
                "has_day_player_change",
            ]
        )

        organization = (participant.organization or "").strip()
        if not organization:
            continue

        field = org1_by_tournament_id.get(participant.category.tournament_id)
        if not field:
            continue

        player_numbers = [1]
        if (participant.player2_name or "").strip():
            player_numbers.append(2)

        for player_no in player_numbers:
            ParticipantOrganizationValue.objects.get_or_create(
                participant_id=participant.id,
                player_no=player_no,
                field_id=field.id,
                defaults={
                    "original_value": organization,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_tournament_default_tournament_reflected_entry_code_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='current_player1_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='current_player1_short_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='current_player2_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='current_player2_short_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='has_day_player_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='original_player1_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='original_player1_short_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='original_player2_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='original_player2_short_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='TournamentOrganizationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_fields', to='core.tournament')),
            ],
            options={
                'ordering': ['display_order', 'code'],
                'unique_together': {('tournament', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ParticipantOrganizationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_no', models.PositiveSmallIntegerField(choices=[(1, 'Player1'), (2, 'Player2')])),
                ('original_value', models.CharField(max_length=255)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_values', to='core.participant')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_values', to='core.tournamentorganizationfield')),
            ],
            options={
                'ordering': ['participant_id', 'player_no', 'field__display_order', 'field__code'],
                'unique_together': {('participant', 'player_no', 'field')},
            },
        ),
        migrations.RunPython(
            migrate_participant_names_and_organizations,
            migrations.RunPython.noop,
        ),
    ]
